//handles registration
export const FULL_NAME_CHANGED = 'FULL_NAME_CHANGED';
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const RETYPE_PASSWORD_CHANGED = 'RETYPE_PASSWORD_CHANGED';
export const HANDLE_REGISTRATION_FORM = 'HANDLE_REGISTRATION_FORM';
export const CREATE_USER = 'CREATE_USER';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAILED = 'USER_CREATE_FAILED';

//handles login
export const HANDLE_LOGIN_FORM = 'HANDLE_LOGIN_FORM';
export const LOGIN_USER = 'LOGIN_USER';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

